version: '3.4'

services:
  catalogdb:
    container_name : catalogdb
    restart : always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  discountdb:
    container_name : discountdb
    restart : always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb        
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
  pgadmin:
    container_name : pgadmin
    restart : always
    environment:
      - PGADMIN_DEFAULT_EMAIL=webdeveloperht@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234             
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
  redisDB:
    container_name : redisDB
    restart : always
    privileged: true
    ports:
      - "6379:1380"   
   
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionStrings=mongodb://catalogdb:27017/"
    depends_on:
      - catalogdb
    ports:
      - "1388:80"        
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
      - REDIS_URI=redis:1380
      - "CacheSettings:ConnectionString=redisDB:6379"      
    ports:
      - "1389:80"       
    depends_on:
      - redisDB 
     
       
  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;" 
    ports:
      - "1390:80"
    depends_on:
      - discountdb
